# Generated by Django 3.2 on 2021-05-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=128)),
                ('week', models.IntegerField()),
                ('section', models.IntegerField()),
            ],
            options={
                'ordering': ['section', 'week'],
            },
        ),
        migrations.CreateModel(
            name='NID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIDuser', models.CharField(max_length=128)),
                ('NIDpassword', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['NIDuser'],
            },
        ),
    ]
